sonar.projectKey=crisiview-api
sonar.projectName=Crisis View API
sonar.projectVersion=1.0

sonar.sources=routes,server.js,db.js,models.js,migration.js,seed.js
sonar.tests=__tests__
sonar.test.inclusions=__tests__/**/*.test.js

sonar.sourceEncoding=UTF-8
sonar.language=js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,coverage/**,**/*.test.js,reports/**,.scannerwork/**
sonar.coverage.exclusions=__tests__/**,migration.js,seed.js,server.js,db.js
